# Generated by Django 3.1.6 on 2021-02-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0004_freecomment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecomment',
            name='author',
        ),
    ]
